### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by jenkoian** [alleyinteractive/wp-seo#106]
Happy to submit a PR if so, but any interest in adding composer support and whilst we're there submitting this to packagist?

**Comment by GFargo** [comment]
Afternoon @jenkoian, composer support has been added to this repo.  

Unfortunately, I do not have the ability to submit this to packagist at this time, but if you're up to the task please do!

**Comment by jenkoian** [comment]
Thanks @GFargo I don't think I can submit for you as is linked to your account/repo.
