### ISSUE TITLE
Consider adding Github -> Packagist integration

### ISSUE THREAD

**Issue by roborourke** [alleyinteractive/wp-seo#112]
Hey, I'd love to be able to pin versions of this plugin in my `composer.json`. It's way easier to keep packagist in sync now by adding the packagist app to your GH org and giving it permission to the relevant repos. After that log in to packagist with github to grant the permissions it needs.

More detailed instructions are here: https://packagist.org/about#how-to-update-packages

**Comment by bcampeau** [comment]
I passed that along to the team for consideration.

**Comment by dlh01** [comment]
Sorry that we didn't get around to this one. All issues that are not bugs are now being closed, as there are no plans for additional feature development for WP SEO.
