### ISSUE TITLE
Add the generated title as the placeholder attribute on post edit

### ISSUE THREAD

**Issue by scottnelle** [alleyinteractive/wp-seo#32]
It may be valuable to add the generated title (based on the default format settings) as the placeholder attribute for the Title Tag, Meta Description, and Meta Keywords input elements on the single post edit screen. This has the effect of previewing the generated title which will help authors determine whether or not they need to fill in custom values.

For new posts, this could be populated with the formatting string itself, rather than trying to build it in real time as people fill fields out.

**Comment by dlh01** [comment]
Sounds pretty cool to me.

**Comment by dlh01** [comment]
Sorry that we didn't get around to this one. All issues that are not bugs are now being closed, as there are no plans for additional feature development for WP SEO.
