### ISSUE TITLE
Consider bundling a formatting tag for the post thumbnail

### ISSUE THREAD

**Issue by dlh01** [alleyinteractive/wp-seo#39]
The tag's value would be the full-size version of the attachment.

**Comment by dlh01** [comment]
Question: Should this formatting tag return a value if `! is_singular()`?

For example, `WP_SEO_Format_Date_Published` does:

```php
if ( is_singular() ) {
	return get_the_date();
}

return false;
```

even though `get_the_date()` would still return a value on an archive page.

We could do the same thing for the post thumbnail:

```php
return ( is_singular() ) ? get_the_post_thumbnail_url( get_the_ID(), 'full' ) : false;
```

But I wonder whether the check makes it harder for a user or developer to predict the tag's behavior?

**Comment by mboynes** [comment]
My instinct is to have it follow the behavior of `WP_SEO_Format_Date_Published`. As long as it's filtered, a developer can elect different behavior for archive pages.

**Comment by dlh01** [comment]
I think following the behavior of `WP_SEO_Format_Date_Published` is also the best course, and it is filterable.

Even so, it seems potentially annoying that a developer who wanted to use the "raw" value of the formatting tag in their filter would have to duplicate the call to `get_the_post_thumbnail_url(). 

I wonder whether, down the line, it might be useful to split the "should display on this page" logic from the "get the value" logic. Right now, both are bundled in `get_value()`.

**Comment by dlh01** [comment]
Added in #59.
