### ISSUE TITLE
Doesn't adhere to WordPress coding standards

### ISSUE THREAD

**Issue by dlh01** [alleyinteractive/wp-seo#42]
As noted in #41, we should fix the plugin's coding standards violations and add `phpcs` to our Travis runs.

**Comment by tareiking** [comment]
I absolutely love this! Using the latest version on WordPress coding standards, these PHPCS tests pass locally - so running travis tests again should pass now : https://travis-ci.org/alleyinteractive/wp-seo

Nice work :tada:

**Comment by dlh01** [comment]
Thanks, @tareiking. I'll close this branch once Travis approves the merge of the 0.12.0 branch into `master`.

**Comment by dlh01** [comment]
Fixed in 0.12.0.
