### ISSUE TITLE
Static `WP_SEO_Settings::$options` is backwards-incompatible

### ISSUE THREAD

**Issue by dlh01** [alleyinteractive/wp-seo#68]
`wp_seo_settings()->options` no longer returns data and generates a notice. If possible, I'd like to gather a couple thoughts about #63 before 0.13.0 is released, but for the moment, I'm creating this as a placeholder for discussion.

cc @davisshaver

**Comment by davisshaver** [comment]
Glad you made this @dlh01 - I wasn't sure the best place to talk about it, but I do think it's worth a conversation before merge. I paid attention to the tests and did some other testing but I know it's a risky move. I checked to see if any themes were using this string but I didn't see any.

**Comment by dlh01** [comment]
Addressed in #72.
