### ISSUE TITLE
More optimal UI when placing the meta box in the sidebar

### ISSUE THREAD

**Issue by johnbillion** [alleyinteractive/wp-seo#69]
When the Search Engine Optimization meta box on the post editing screen is moved into the sidebar, the UI gets a little cramped. See screenshot below.

If the `th` and `td` cells were given a `display:block` rule when the meta box is in the sidebar, they'd stack vertically, resulting in more space.

Before:

<img width="295" alt="screenshot 2017-01-20 12 49 58" src="https://cloud.githubusercontent.com/assets/208434/22150156/7bca58ee-df0f-11e6-9f1c-f4ace2a45f57.png">

After:

<img width="294" alt="screenshot 2017-01-20 12 59 15" src="https://cloud.githubusercontent.com/assets/208434/22150326/53397ab2-df10-11e6-84bd-f449d11ff895.png">

**Comment by davisshaver** [comment]
@johnbillion Seems like a good tweak to me.  See https://github.com/alleyinteractive/wp-seo/pull/70

![screen shot 2017-01-20 at 3 05 00 pm](https://cloud.githubusercontent.com/assets/1636964/22163728/053e4998-df22-11e6-9abe-3f17ebf6667f.png)

![screen shot 2017-01-20 at 3 05 05 pm](https://cloud.githubusercontent.com/assets/1636964/22163719/fbaf19e8-df21-11e6-99b5-67e17b5fabdb.png)

**Comment by dlh01** [comment]
This fix has been merged as part of v0.13. Please feel free to reopen if any problems with it arise.
