### ISSUE TITLE
Reorganize settings page

### ISSUE THREAD

**Issue by mboynes** [alleyinteractive/wp-seo#7]
The settings page needs some UX lovin'. Here are the accordion boxes currently:
- Home Page
- Post types
- Single Post Defaults
- Single Page Defaults
- Single Media Defaults
- Single Guest Author Defaults
- Taxonomies
- Category Archives
- Tag Archives
- Format Archives
- Author Archives
- Date Archives
- Search Results
- 404 Page
- Other Meta Tags 

Here's what I propose we break this down to:
- Site-Wide Meta Tags
- Home Page
- Post types
  - Single Post Defaults
  - Single Page Defaults
  - Single Media Defaults
  - [Custom post type] Defaults
- Taxonomies
  - Category Archives
  - Tag Archives
  - Format Archives
  - [Custom taxonomy defaults]
- Archives
  - Generic Archives
  - Author Archives
  - Date Archives
  - Search Results
- -404 Page- (I don't think it's necessary to optimize the meta fields of a 404 page, since they don't get indexed)

The second-level bullets would be sections within the accordion. Here's an (unpolished) example that should give you an idea of what I'm envisioning:

![wp-seo-settings](https://cloud.githubusercontent.com/assets/465154/3708335/a4207bb6-1441-11e4-97c4-01e2899dda0e.jpg)

**Comment by bcampeau** [comment]
In addition, inactive post types should disappear from the page.
