### ISSUE TITLE
Should extensions be encouraged to store data in the plugin option?

### ISSUE THREAD

**Issue by dlh01** [alleyinteractive/wp-seo#79]
Breaking out a discussion started in #63 and #72:

> More generally, should extensions be encouraged to store data in the core plugin option? One argument against that is that the core plugin couldn't change its option structure in the future without risking overwriting an extension's data.

> The same question applies to the new $whitelisted_fields property. In the case of $whitelisted_fields, though, I can see the convenience for extensions of being able to have WP SEO handle the legwork of saving keys for you if you need the same pre-save checks as the plugin core fields (not sure about the implications of sharing the nonce, though).

> Counterpoint: Should new plugins try to use core's recently enhanced register_meta()? Do we know yet how nicely WP SEO interacts with plugins that do use it (or, if you did try, what happened)? The same could be asked of core's recently enhanced register_setting().

The 0.13.0 branch currently contains filters that would be affected by this question, e.g. `wp_seo_sanitize_as_text_field`.

For `$whitelisted_fields`, one idea I was thinking about was adding an action at the end of `save_post_fields()` and `save_term_fields()` to signal that data could be safely saved. The core plugin could use these hooks, too, much like it does the actions in `wp_seo_the_post_meta_fields()` and `wp_seo_the_add_term_meta_fields()`.

**Comment by davisshaver** [comment]
Switching to hooks seems like it'd be more verbose to achieve pretty much the same outcome as `$whitelisted_fields`.... could you expand on the risk reduction point a little more, not sure I follow how this would work

**Comment by dlh01** [comment]
> Switching to hooks seems like it'd be more verbose to achieve pretty much the same outcome as $whitelisted_fields

Hooks are just one idea, but I grant you that they would be more verbose. I'm mostly thinking about how to avoid what I see as two potential maintenance burdens:

1. For the plugin, it's unclear to me what we're committing to doing with whitelisted fields. For example, if we add a meta box to the edit-user screen, does that mean the whitelisted fields will be automatically added? As a developer, how would I opt-out of that if I needed to? Why wouldn't whitelisted fields also be automatically added to the settings meta boxes?

1. For developers, if you have SEO meta that can't be sanitized with `sanitize_text_field()`, then you would still need a separate routine for saving those fields in addition to (or instead of) filtering `$whitelisted_fields`.

On the `register_meta()` point, here's a sketch of an approach that uses it:

```php
<?php

$seo_meta = array_map( 'sanitize_text_field', wp_unslash( $_POST['seo_meta'] ) );
$seo_keys = array_map( 'sanitize_text_field', array_keys( $seo_meta ) );

foreach ( $seo_keys as $key ) {
	$meta_key = $key;

	if ( in_array( $meta_key, array( 'title', 'description', 'keywords' ), true ) ) {
		$meta_key = "_meta_{$meta_key}";
	}

	if ( ! has_filter( "sanitize_post_meta_{$meta_key}" ) ) {
		continue;
	}

	if ( isset( $_POST['seo_meta'][ $key ] ) ) {
		$meta_value = sanitize_meta( $meta_key, wp_unslash( $_POST['seo_meta'][ $key ] ), 'post' );
		update_post_meta( $post_id, wp_slash( $meta_key ), wp_slash( $meta_value ) );
	}
}
```

This has some of the convenience of `$whitelisted_fields` in that it handles any keys in `$_POST['seo_meta']` while allowing more control over sanitizing.

But maybe, as a developer, I would also then expect `$_POST['seo_meta']` to receive similar treatment everywhere, which brings us back to point (1).

> could you expand on the risk reduction point a little more, not sure I follow how this would work

Because `wp_seo_sanitize_as_text_field` and `wp_seo_sanitize_as_integer` allow extensions to add arbitrary keys to the core plugin's option array, the core plugin could never add new keys to the option array without potentially overwriting the data managed by an extension. If extensions were not given such direct access to the core plugin option, and instead encouraged to store data in their own options, I think that would reduce the risk of overwriting.

**Comment by davisshaver** [comment]
@dlh01 I see where you are coming from but I am less worried about developer experience at this point. The current barriers to entry could be seen as an advantage if we want to reduce risk around data model. With some documentation effort we can probably make the implementations conceptually easier to understand too.

I'm game to tackle a refactor down these lines, but I don't have a strong opinion on whether it's architecturally necessary.

**Comment by dlh01** [comment]
> The current barriers to entry could be seen as an advantage if we want to reduce risk around data model.

Could you elaborate on this idea? Sorry, I'm not sure I understand yet.

**Comment by davisshaver** [comment]
Security through obscurity :). If we are worried about WP SEO data being corrupted, having the extension implementation be verbose could act as an advantage.
	





On Tue, Apr 18, 2017 at 10:24 AM -0400, "David Herrera" <notifications@github.com> wrote:













The current barriers to entry could be seen as an advantage if we want to reduce risk around data model.



Could you elaborate on this idea? Sorry, I'm not sure I understand yet.

**Comment by dlh01** [comment]
Heh, I might not be describing what I mean clearly enough, at least with `filter_wp_seo_sanitize_as_text_field` and `filter_wp_seo_sanitize_as_integer`. I was worried about WP SEO corrupting someone else's data, not the other way around.

**Comment by davisshaver** [comment]
Understood @dlh01 – how should we proceed?

**Comment by dlh01** [comment]
I'm not sure. Can anyone else chime in with an argument about it, especially if you have a theme or plugin that it affects?

**Comment by dlh01** [comment]
@davisshaver Regarding post and term meta, what would you think of an approach like this one: https://github.com/alleyinteractive/wp-seo/commit/9d55d4d8aa5717746f7367fab88dd31c6a5c955c? (Example usage is at the bottom.)

This expands on `$whitelisted_fields` so that it acts like a wrapper for `register_meta()`. The `sanitize_callback` argument should handle cases where `sanitize_text_field()` is insufficient, and the relationship to `register_meta()` should help clarify where it will be used in the future.

I'm using the pre-4.6 `register_meta()` parameters, but once WP SEO increases its minimum required version to 4.6, we could support the new parameters and, hopefully, get a lot of the benefits along with them.

Note also that this approach saves all new term meta as actual term meta.

**Comment by davisshaver** [comment]
This is my first time seeing `register_meta()` and I get why you see the benefit. I like this approach. What else would you want to see in WP SEO to support it? I can refactor WP SEO Social to reflect what you've got currently.
