### ISSUE TITLE
`WP_SEO_Fields` and new admin template tags

### ISSUE THREAD

**Issue by dlh01** [alleyinteractive/wp-seo#80]
This discussion began in #63:

> I see that in WP SEO Social you're able to use the render_dropdown() and render_image_field() in the post and term-editing screens. It's great that the functions are reusable, but in that case, why should they be in WP_SEO_Settings? Since that class is (at least nominally) only about managing the settings page and core plugin option, couldn't it draw from rendering methods from outside the class rather than having third parties go through it?

#72 moved things forward by introducing `WP_SEO_Fields`. There are a few points about the class that I was wondering about:

- The central `field()` method gets data from the plugin option value. So, in practice, I'm not sure how it would be used outside of the settings page.

- The markup for some of the methods that were ported from `WP_SEO_Settings` is still fairly tightly coupled to the needs of the settings page. Would it be feasible, or beneficial, to test whether the methods are generally applicable by trying to use them in `admin-template.php`?

- Speaking of, `admin-template.php` is where new administration template tags have been added over the last few releases. Is it worth adding the new markup-generating functions into that file instead of a class for consistency?

**Comment by davisshaver** [comment]
@dlh01 It would be beneficial if there is user benefit I think. Regarding file structure, yes `WP_SEO_Fields` uses the option values if no value is passed, but the move out of `WP_SEO_Settings` had been motivated by keeping the logic discrete and file length reasonable. Do we want to work on making WP SEO `admin-template.php` more like WP SEO Social, where we are using the `WP_SEO_Fields` class to render the fields? https://github.com/alleyinteractive/wp-seo-social/blob/master/php/admin-template.php#L57

**Comment by dlh01** [comment]
> yes WP_SEO_Fields uses the option values if no value is passed, but the move out of WP_SEO_Settings had been motivated by keeping the logic discrete and file length reasonable

Fair. I would offer that at least `field()` should stay in `WP_SEO_Settings` because it doesn't currently make sense to call it from outside the settings context.

We also need to provide backwards-compatibility for the methods removed from `WP_SEO_Settings`.

> Do we want to work on making WP SEO admin-template.php more like WP SEO Social, where we are using the WP_SEO_Fields class to render the fields?

Yeah, I was leaning toward something like that. I had been thinking of it the other way around, though: Make the new methods in `WP_SEO_Fields` into template functions in `admin-template.php` for consistency with what's there now. I don't have a strong preference, but I'm not sure what the benefit of a class is at this point, given that there are no hooks or stored data in it.

**Comment by davisshaver** [comment]
Got most of this covered in #89. 

Re,
>  I don't have a strong preference, but I'm not sure what the benefit of a class is at this point, given that there are no hooks or stored data in it.

I went with the class for encapsulation and structure, but I see your point. Is this a performance benefit to moving away from classes?

**Comment by dlh01** [comment]
> Is this a performance benefit to moving away from classes?

I don't mean to suggest a permanent move away from classes; it's more that I'm uncertain about whether we need the infrastructure at this point.

In the case of `render_textarea()`, `render_checkboxes()`, `render_repeatable_field()`, and `render_text_field()`: While I would agree that they don't really belong in `WP_SEO_Settings`, nothing currently in WP SEO Social or the other changes planned for this release require that they be moved (I don't think? Correct me if needed).

For `render_dropdown()` and `render_image_field()`, then, as alluded to above, a template tag could provide the functionality we need now while remaining consistent with the other functions in `admin-template`. It's not really encapsulation, but `-template` is at least sort of a WordPress-y structure.

**Comment by davisshaver** [comment]
@dlh01 In WP SEO Social, we use the `WP_SEO_Fields()` class. Making these global scope template tags WFM if that's the direction you want to go. WP SEO Social is moving into production soon for Tech of News and it'd be nice to have this settled before we have anything in the wild.

**Comment by dlh01** [comment]
> In WP SEO Social, we use the WP_SEO_Fields() class

Right, sorry, I meant was there something about the previous setup that made it difficult for writing WP SEO Social and that `WP_SEO_Fields` makes easier?

**Comment by davisshaver** [comment]
@dlh01 Not necessarily, just that using the whole WP_SEO_Settings class to render fields felt unwieldy.

**Comment by davisshaver** [comment]
@dlh01 Did you want to merge https://github.com/alleyinteractive/wp-seo/issues/89 or go another direction?
