### ISSUE TITLE
Provide Filter to Meta Description and other meta fields.

### ISSUE THREAD

**Issue by achaitanyajami** [alleyinteractive/wp-seo#99]
I am trying to modify my meta description from my theme and unable to modify, since we are having
`$this->meta_field( 'description', $meta_description )` at line [553](https://github.com/alleyinteractive/wp-seo/blob/master/php/class-wp-seo.php#L553)

**My scenario**
if I have Title, use Title else uses meta description.

From the above code, At line no 541 I can only apply filter `wp_seo_meta_description_format` if I don't have a meta description.

But in my case, I need both since I am using meta description for og:description.

So, I decided to made changes in [File](https://github.com/alleyinteractive/wp-seo/blob/master/php/class-wp-seo.php) at `meta_field` method, so then we can modify any meta tag content easily using the filter.

**My code:** at line 500 will be 
`$content = apply_filters( 'wp_seo_meta_field', $content, $name );`

So, I can easily apply my filters to any meta tags used by WP-SEO like
`function meta_feild_content($content, $name){ /* mycode goes here */
return $content;
}`
`add_filter( 'wp_seo_meta_field', 'meta_field_content', 10, 2 ); `

Since I don't have permission it accesses this repo, I am unable to push the code.

If you think my approach is good can you ad the code.

Thanks
Arun

**Comment by mboynes** [comment]
He @achaitanyajami,
Thanks for the suggestion! After reviewing the code, I agree that it would be helpful to add a filter to the `meta_field()` method. I expect that we'll be able to put a PR together mid-to-late next-week for that.

**Comment by achaitanyajami** [comment]
Sure @mboynes,

**Comment by dlh01** [comment]
Hey @achaitanyajami -- let me know whether the filter added in #100 would do what you're looking for.

**Comment by achaitanyajami** [comment]
Hi @dlh01, this looks good to me.

Thanks for the changes.

**Comment by achaitanyajami** [comment]
Add the comment in the PR.

**Comment by dlh01** [comment]
Thanks @achaitanyajami! This fix has been merged as part of v0.13.
